JobSearch/Controllers/ApplyJobController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobSearch.Models;

namespace JobSearch.Controllers
{
    public class ApplyJobController : Controller
    {
        dbJobSearchEntities dbobj = new dbJobSearchEntities();
        // GET: ApplyJob
        public ActionResult ApplyJob_Load(int cid, int jid)        
        {
            TempData["cid"] = cid;
            TempData["jid"] = jid;
            return View();
        }

        public ActionResult ApplyJob_Click(ApplyJob clsobj,DisplayAllnSearch obj,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {                
                if (file.ContentLength > 0)
                {
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/FResume");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);

                    var fullpath = Path.Combine("~\\FResume", fname);
                    clsobj.Resume = fullpath;
                }

                int uid = Convert.ToInt32(Session["uid"]);
                int cid = Convert.ToInt32(TempData["cid"]);
                int jid = Convert.ToInt32(TempData["jid"]);

                dbobj.sp_ApplyJob(jid, cid, uid, clsobj.Date, clsobj.Resume, "Available");
                clsobj.msg = "Applied Successfully";

                return View("ApplyJob_Load", clsobj);
            }
            return View("ApplyJob_Load", clsobj);
        }
    }
}

JobSearch/Controllers/DisplayAllJobController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobSearch.Models;

namespace JobSearch.Controllers
{
    public class DisplayAllJobController : Controller
    {
        dbJobSearchEntities dbobj = new dbJobSearchEntities();
        // GET: DisplayAllJob
        public ActionResult DisplayAllJob_Load()
        {
            return View(GetData());
        }
        private DisplayAllnSearch GetData()
        {
            var joblist = new DisplayAllnSearch();
            List<string> lst = new List<string>();
            var job = dbobj.tbAddJobs.ToList();
            foreach(var e in job)
            {
                var jobcls = new jsearch();
                jobcls.JobId = e.JobId;
                jobcls.CId = e.CId;
                jobcls.JobName = e.JobName;
                jobcls.Vacancy = e.Vacancy;
                jobcls.RequiredSkill = e.RequiredSkill;
                jobcls.Experience = e.Experience;
                jobcls.Qualification = e.Qualification;
                jobcls.Salary = e.Salary;
                jobcls.Location = e.Location;
                jobcls.StartDate = e.StartDate;
                jobcls.EndDate = e.EndDate;
                jobcls.JobStatus = e.JobStatus;

                joblist.selectjob.Add(jobcls);
                var s = jobcls.RequiredSkill;
                lst.Add(s);
                TempData["ski"] = string.Join(" ", lst);
            }
            return joblist;
        }
        public ActionResult SearchJob_Click(DisplayAllnSearch clsobj)
        {
            string qry = "";
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.JobName))
            {
                qry += " and JobName like '%" + clsobj.insertse.JobName + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.RequiredSkill))
            {
                qry += " and RequiredSkill like '%" + clsobj.insertse.RequiredSkill + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.Location))
            {
                qry += " and Location like '%" + clsobj.insertse.Location + "%'";
            }
            return View("DisplayAllJob_Load", getdata1(clsobj, qry));
        }
        private DisplayAllnSearch getdata1(DisplayAllnSearch clsobj,string qry)
        {
            using (var con=new SqlConnection(ConfigurationManager.ConnectionStrings["test"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("sp_check", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@qry", qry);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                var joblist = new DisplayAllnSearch();
                while (dr.Read())
                {
                    var jobcls = new jsearch();
                    jobcls.JobId = Convert.ToInt32(dr["JobId"].ToString());
                    jobcls.CId = Convert.ToInt32(dr["CId"].ToString());
                    jobcls.JobName = dr["JobName"].ToString();
                    jobcls.Vacancy = Convert.ToInt32(dr["Vacancy"].ToString());
                    jobcls.RequiredSkill = dr["RequiredSkill"].ToString();
                    jobcls.Experience = dr["Experience"].ToString();
                    jobcls.Qualification = dr["Qualification"].ToString();
                    jobcls.Salary = Convert.ToInt32(dr["Salary"].ToString());
                    jobcls.Location = dr["Location"].ToString();
                    jobcls.StartDate = Convert.ToDateTime(dr["StartDate"].ToString());
                    jobcls.EndDate = Convert.ToDateTime(dr["EndDate"].ToString());
                    jobcls.JobStatus = dr["JobStatus"].ToString();
                    joblist.selectjob.Add(jobcls);
                }
                con.Close();
                return joblist;
            }
        }
    }
}

JobSearch/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobSearch.Models;

namespace JobSearch.Controllers
{
    public class UserLoginController : Controller
    {
        dbJobSearchEntities dbobj = new dbJobSearchEntities();
        // GET: UserLogin
        public ActionResult Login_Pageload()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            return View();
        }
        public ActionResult CompanyHome()
        {
            return View();
        }
        public ActionResult Login_Click(Login clsobj)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_LoginCheck(clsobj.Username, clsobj.Password, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    var uid = dbobj.sp_LogId(clsobj.Username, clsobj.Password).FirstOrDefault();
                    Session["uid"] = uid;

                    var lt = dbobj.sp_LogType(clsobj.Username, clsobj.Password).FirstOrDefault();
                    if (lt == "User")
                    {
                        return RedirectToAction("UserHome");
                    }
                    else if (lt == "Company")
                    {
                        return RedirectToAction("CompanyHome");
                    }
                }
                else
                {
                    ModelState.Clear();
                    clsobj.Msg = "Invalid Login";
                    return View("Login_Pageload", clsobj);
                }
            }
            return View("Login_Pageload", clsobj);
        }
    }
}

JobSearch/Views/DisplayAllJob/DisplayAllJob_Load.cshtml
@model JobSearch.Models.DisplayAllnSearch
@{
    ViewBag.Title = "DisplayAllJob_Load";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All Jobs</h2>


<div>
    @using (Html.BeginForm("SearchJob_Click", "DisplayAllJob", FormMethod.Post))
            {
                <table>
                    <tr>
                        <td><label>JobName</label></td>
                        <td>@Html.TextBoxFor(m => m.insertse.JobName)</td>

                        <td><label>Skills</label></td>
                        <td>@Html.TextBoxFor(m => m.insertse.RequiredSkill)</td>

                        <td><label>Location</label></td>
                        <td>@Html.TextBoxFor(m => m.insertse.Location)</td>

                        <td><input type="submit" value="Search"/></td>
                    </tr>
                </table>
            }
    </div>

<div>
    @using (Html.BeginForm("DisplayAllJob_Load", "DisplayAllJob", FormMethod.Get))
    {
        if (Model != null)
        {
            if (Model.selectjob != null && Model.selectjob.Count != 0)
            {
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.JobName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.Vacancy)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.RequiredSkill)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.Experience)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.Qualification)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.Salary)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.Location)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.StartDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.EndDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.JobStatus)
                        </th>
                    </tr>

                    @foreach (var item in Model.selectjob)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.JobName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Vacancy)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RequiredSkill)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Experience)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Qualification)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Salary)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Location)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StartDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EndDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.JobStatus)
                            </td>

                            <td>
                                @Html.ActionLink("Apply Now", "ApplyJob_Load", "ApplyJob", new { cid = item.CId, jid = item.JobId }, null)
                               
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <script>
                    alert('No matching jobs found');
                </script>
            }
        }
    }
    <div>
        @Html.ActionLink("Back to Home", "UserHome","UserLogin")
    </div>
</div>