JobSearch/Controllers/CompanyRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobSearch.Models;

namespace JobSearch.Controllers
{
    public class CompanyRegController : Controller
    {
        dbJobSearchEntities dbobj = new dbJobSearchEntities();
        // GET: CompanyReg
        public ActionResult Company_Load()
        {
            return View();
        }
        public ActionResult Company_Click(CompanyRegistration clsobj)
        {
            if (ModelState.IsValid)
            {
                var getmaxid = dbobj.sp_MaxIdLogin().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                dbobj.sp_CompanyReg(regid, clsobj.Name, clsobj.Address, clsobj.Email, clsobj.Phone, "Available");
                dbobj.sp_Login(regid, clsobj.Username, clsobj.Password, "Company");
                clsobj.Msg = "Registered Successfully";
                return View("Company_Load", clsobj);
            }
            return View("Company_Load", clsobj);
        }
    }
}

JobSearch/Views/CompanyReg/Company_Load.cshtml
@model JobSearch.Models.CompanyRegistration
@{
    ViewBag.Title = "Company_Load";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Company Registration</h2>
<div>
    @using (Html.BeginForm("Company_Click", "CompanyReg", FormMethod.Post))
    {
        <div>
            <label>Company Name :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name)
        </div>

        <div>
            <label>Company Address :</label>
        </div>
        <div>
            @Html.TextAreaFor(m => m.Address)
            @Html.ValidationMessageFor(m => m.Address)
        </div>

        <div>
            <label>Email :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
        </div>

        <div>
            <label>Phone :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Phone)
            @Html.ValidationMessageFor(m => m.Phone)
        </div>       

        <div>
            <label>Username:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Username)
            @Html.ValidationMessageFor(m => m.Username)
        </div>

        <div>
            <label>Password :</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password)
        </div>

        <div>
            <label>Confirm Password :</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.CPassword)
            @Html.ValidationMessageFor(m => m.CPassword)
        </div>

        <div>
            <input type="submit" value="Register" />
            @Html.DisplayFor(m => m.Msg)
        </div>
    }
</div>