JobSearch/Controllers/UserRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobSearch.Models;

namespace JobSearch.Controllers
{
    public class UserRegController : Controller
    {
        dbJobSearchEntities dbobj = new dbJobSearchEntities();
        // GET: UserReg
        public ActionResult User_Load()
        {

            //dropdown
            List<stclass> stList = new List<stclass>//object
            {
                new stclass{sId=1,sName="Kerala"},
                new stclass {sId=2,sName="Tamilnadu"},
                new stclass {sId=3,sName="Karnataka"}
            };
            ViewBag.Selstates = new SelectList(stList, "sId", "sName");//viewbag to pass value from controller to view

            //checkbox list
            UserRegistration user = new UserRegistration();//object of main class UserInsert
            user.MyFavoriteQual = getQualificationData();
            return View(user);
        }

        //checkbox list
        public List<CheckBoxListHelper> getQualificationData()
        {
            List<CheckBoxListHelper> sts = new List<CheckBoxListHelper>()
            {
                new CheckBoxListHelper{Value="SSLC",Text="SSLC",IsChecked=true},
                new CheckBoxListHelper{Value="PLUS TWO",Text="PLUS TWO",IsChecked=false},
                new CheckBoxListHelper{Value="BCA",Text="BCA",IsChecked=false},
                new CheckBoxListHelper{Value="MCA",Text="MCA",IsChecked=false},
                new CheckBoxListHelper{Value="BTech",Text="BTech",IsChecked=false},

            };
            return sts;
        }
        public ActionResult User_Click(UserRegistration clsobj,FormCollection form)
        {
            if (ModelState.IsValid)
            {

                var getmaxid = dbobj.sp_MaxIdLogin().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }

                //dropdown
                List<stclass> stList = new List<stclass>//object
            {
                new stclass{sId=1,sName="Kerala"},
                new stclass {sId=2,sName="Tamilnadu"},
                new stclass {sId=3,sName="Karnataka"}
            };
                int selectedId = Convert.ToInt32(form["Selstates"]);
                stclass selectedItem = stList.FirstOrDefault(c => c.sId == selectedId);
                clsobj.sId = selectedItem.sId;//set
                clsobj.sName = selectedItem.sName;//set

                ViewBag.Selstates = new SelectList(stList, "sId", "sName");

                //checkbox
                var quid = string.Join(",", clsobj.selectedQual);//join selected items with comma and saved in quid
                clsobj.Qualification = quid;//set
                clsobj.MyFavoriteQual = getQualificationData();//get


               
                dbobj.sp_UserReg(regid, clsobj.Name, clsobj.Address, clsobj.Age, clsobj.Gender, clsobj.Phone, clsobj.Email, clsobj.sName, clsobj.District, clsobj.Pincode, clsobj.Qualification, clsobj.CGPA, clsobj.Skills, "Available");
                dbobj.sp_Login(regid, clsobj.Username, clsobj.Password, "User");
                clsobj.Msg = "Registered Successfully";
                return View("User_Load", clsobj);
            }
            else
            {
                List<stclass> stList = new List<stclass>//object
            {
                new stclass{sId=1,sName="Kerala"},
                new stclass {sId=2,sName="Tamilnadu"},
                new stclass {sId=3,sName="Karnataka"}
            };
                ViewBag.Selstates = new SelectList(stList, "sId", "sName");//viewbag to pass value from controller to view

                //checkbox list
                var quid = string.Join(",", clsobj.selectedQual);//join selected items with comma and saved in quid
                clsobj.Qualification = quid;//set
                clsobj.MyFavoriteQual = getQualificationData();//get


                return View("User_Load", clsobj);
            }
            return View("User_Load", clsobj);
        }
    }
}

JobSearch/Views/UserReg/User_Load.cshtml
@model JobSearch.Models.UserRegistration
@{
    ViewBag.Title = "User_Load";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Registration</h2>
<div>
    @using (Html.BeginForm("User_Click", "UserReg", FormMethod.Post))
    {
        <div>
            <label>Name </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name)
        </div>

        <div>
            <label>Address </label>
        </div>
        <div>
            @Html.TextAreaFor(m => m.Address)
            @Html.ValidationMessageFor(m => m.Address)
        </div>

        <div>
            <label>Age </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Age)
            @Html.ValidationMessageFor(m => m.Age)
        </div>

        <div>
            <label>Gender </label>
        </div>
        <div>
            Male
            @Html.RadioButtonFor(model => model.Gender, "Male")
            Female
            @Html.RadioButtonFor(model => model.Gender, "Female")
        </div>

        <div>
            <label>Phone </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Phone)
            @Html.ValidationMessageFor(m => m.Phone)
        </div>

        <div>
            <label>Email </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
        </div>

        <div>
            <label>State </label>
        </div>
        <div>
             @Html.DropDownList("Selstates", (SelectList)ViewBag.Selstates, "--Select--", new { @class = "form-control" })
            
        </div>

        <div>
            <label>District </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.District)
            @Html.ValidationMessageFor(m => m.District)
        </div>

        <div>
            <label>Pincode </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Pincode)
            @Html.ValidationMessageFor(m => m.Pincode)
        </div>

        <div>
            <label>Qualiffication </label>
        </div>
        <div>
            @foreach (var item in Model.MyFavoriteQual)
            {
                <label>
                    <input type="checkbox" value="@item.Value" checked="@item.IsChecked" name="selectedQual" id="@item.Value" />
                    @Html.Raw(item.Text)
                </label>
            }
            
        </div>

        <div>
            <label>CGPA </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.CGPA)
            @Html.ValidationMessageFor(m => m.CGPA)
        </div>

        <div>
            <label>Skills </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Skills)
            @Html.ValidationMessageFor(m => m.Skills)
        </div>

        <div>
            <label>Username </label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Username)
            @Html.ValidationMessageFor(m => m.Username)
        </div>

        <div>
            <label>Password </label>
        </div>
        <div>
            @Html.PasswordFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password)
        </div>

        <div>
            <label>Confirm Password </label>
        </div>
        <div>
            @Html.PasswordFor(m => m.CPassword)
            @Html.ValidationMessageFor(m => m.CPassword)
        </div>
        <div>
            <input type="submit" value="Register" />
            @Html.DisplayFor(m => m.Msg)
        </div>
    }
</div>