JobSearch/Models/AddJob.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JobSearch.Models
{
    public class AddJob
    {
        public int CId { get; set; }
        [Required(ErrorMessage ="Enter Job Name")]
        public string JobName { get; set; }
        [Required(ErrorMessage = "Enter Number of Vaccancy")]
        public int Vacancy { get; set; }
        [Required(ErrorMessage = "Enter Skills Required")]
        public string RequiredSkill { get; set; }
        [Required(ErrorMessage = "Enter Required Experience")]
        public string Experience { get; set; }
        [Required(ErrorMessage = "Enter Required Qualification")]
        public string Qualification { get; set; }
        [Required(ErrorMessage = "Enter Salary")]
        public int Salary { get; set; }
        [Required(ErrorMessage = "Enter Location")]
        public string Location { get; set; }
        [Required(ErrorMessage = "Enter Start Date")]
        public System.DateTime StartDate { get; set; }
        [Required(ErrorMessage = "Enter End Date")]
        public System.DateTime EndDate { get; set; }
        public string Msg { set; get; }
    }
}

JobSearch/Controllers/AddJobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobSearch.Models;

namespace JobSearch.Controllers
{
    public class AddJobController : Controller
    {
        dbJobSearchEntities dbobj = new dbJobSearchEntities();
        // GET: AddJob
        public ActionResult Addjob_Load()
        {
            return View();
        }
        public ActionResult addjob_Click(AddJob clsobj)
        {
            if (ModelState.IsValid)
            {
               
                int cid = Convert.ToInt32(Session["uid"]);

                dbobj.sp_AddJob(cid, clsobj.JobName, clsobj.Vacancy, clsobj.RequiredSkill, clsobj.Experience, clsobj.Qualification, clsobj.Salary, clsobj.Location, clsobj.StartDate, clsobj.EndDate, "Available");
                clsobj.Msg = "Job Posted";
                return View("Addjob_Load", clsobj);               
            }
            return View("Addjob_Load", clsobj);       
        }
    }
}

JobSearch/Views/AddJob/Addjob_Load.cshtml
@model JobSearch.Models.AddJob
@{
    ViewBag.Title = "Addjob_Load";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add job</h2>
<div>
    @using (Html.BeginForm("addjob_Click","AddJob", FormMethod.Post))
    {
        <div>
            <label>Job Name :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.JobName)
            @Html.ValidationMessageFor(m => m.JobName)
        </div>

        <div>
            <label>Number of Vaccancy :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Vacancy)
            @Html.ValidationMessageFor(m => m.Vacancy)
        </div>

        <div>
            <label>Skills Required :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.RequiredSkill)
            @Html.ValidationMessageFor(m => m.RequiredSkill)
        </div>

        <div>
            <label>Experience :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Experience)
            @Html.ValidationMessageFor(m => m.Experience)
        </div>

        <div>
            <label>Job Qualification :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Qualification)
            @Html.ValidationMessageFor(m => m.Qualification)
        </div>

        <div>
            <label>Salary :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Salary)
            @Html.ValidationMessageFor(m => m.Salary)
        </div>

        <div>
            <label>Location :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Location)
            @Html.ValidationMessageFor(m => m.Location)
        </div>

        <div>
            <label>Start Date :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.StartDate)
            @Html.ValidationMessageFor(m => m.StartDate)
        </div>

        <div>
            <label>End Date :</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.EndDate)
            @Html.ValidationMessageFor(m => m.EndDate)
        </div>

        <div>
            <input type="submit" value="Post" />
            @Html.DisplayFor(m => m.Msg)
        </div>
    }
</div>